<a href="https://colab.research.google.com/github/RenatoTente/praticas/blob/main/Aula_de_Analise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Passo a Passo da soluçao do desafio

In [ ]:
# passo 0 - Entender o desafio
# passo 1 - Percorrer todos os arquivos da pasta de base de dados

In [5]:
import os #para mexer em pastas de arquivos no pc, etc
import pandas as pd
lista_arquivo = os.listdir("/content/drive/MyDrive/Vendas")
display(lista_arquivo)

['Devolucoes - São Paulo.csv',
 'Vendas - Porto Alegre.csv',
 'Devolucoes - Recife.csv',
 'Devolucoes - Porto Alegre.csv',
 'Vendas - Fortaleza.csv',
 'Devolucoes - Goiás.csv',
 'Vendas - Salvador.csv',
 'Devolucoes - Rio de Janeiro.csv',
 'Devolucoes - Salvador.csv',
 'Devolucoes - Curitiba.csv',
 'Vendas - Rio de Janeiro.csv',
 'Devolucoes - Fortaleza.csv',
 'Vendas - São Paulo.csv',
 'Vendas - Belo Horizonte.csv',
 'Devolucoes - Belo Horizonte.csv',
 'Vendas - Recife.csv',
 'Vendas - Goiás.csv',
 'Vendas - Curitiba.csv']

In [10]:
tabela_total = pd.DataFrame()  #criar uma tabela vazia, vamos juntar os documentos todos em apenas 1

# passo 2 - Importar a base de dados de vendas
for arquivo in lista_arquivo:
#se tem "vendas" dentro do arquivo se usar o not antes de vendas mostra tudo o resto sem vendas
  if "Vendas" in arquivo:  #arquivo.lower() ele ia mostrar com as maiusculas e minusculas
   # print(f"/content/drive/MyDrive/Vendas/{arquivo}")  #formatar uma variavel dentro dele usar o f
    tabela = pd.read_csv(f"/content/drive/MyDrive/Vendas/{arquivo}")
    #print(arquivo)
    #display(tabela)
    tabela_total = tabela_total.append(tabela)  #adicionamos a nossa tabela à tabela criada por nos em cima

# passo 3 - Tratar/ compilar base de dados

display(tabela_total)

,Unnamed: 0,SKU,Produto,Quantidade Vendida,Primeiro Nome,Sobrenome,Data,Loja,Preco Unitario,Unnamed: 8
0,14,HL4379,Televisão,4,Ylana,Teraoka,6/23/2018,Porto Alegre,2500,NaN
1,34,HL1148,Câmera,1,Rubens,Netto,7/11/2018,Porto Alegre,2100,NaN
2,43,HL1148,Câmera,5,Paloma,Sperandei,9/15/2018,Porto Alegre,2100,NaN
3,49,HL8851,Notebook,5,Breno,Farias,6/24/2018,Porto Alegre,3500,NaN
4,52,HL4379,Televisão,2,Lorena,Kohn,7/31/2018,Porto Alegre,2500,NaN
...,...,...,...,...,...,...,...,...,...,...
714,9859,HL2714,Tablet,1,Júlio,Fraga,12/25/2018,Curitiba,1600,NaN
715,9876,HL4379,Televisão,5,Bruno,Mota,4/30/2018,Curitiba,2500,NaN
716,9918,HL1148,Câmera,2,Lucas,Reis,12/27/2018,Curitiba,2100,NaN
717,9944,HL1918,iPhone,5,Raphael,Kurtz,7/16/2018,Curitiba,5300,NaN
718,9998,HL7348,SmartWatch,1,Vinícius,Antunes,12/10/2018,Curitiba,1400,NaN

In [14]:
# passo 4 - Calcular o produto mais vendido em (quantidade),  agrupar os produtos e somar a quantidade vendida .sum para juntar os valores das restantes tabelas

tabela_produtos = tabela_total.groupby("Produto").sum()  
tabela_produtos = tabela_produtos[["Quantidade Vendida", "Preco Unitario"]].sort_values(by="Quantidade Vendida", ascending =False)
#sort_values para ordenar por valores, ascending ordem ascendente
display(tabela_produtos)

            Quantidade Vendida  Preco Unitario
Produto
iPhone                    8974        15778100
Televisão                 5931         4905000
Notebook                  3249         3717000
Android                   3183         3631200
SmartWatch                2980         1393000
Tablet                    2921         1556800
Câmera                    2805         2020200

In [19]:
# passo 5 - Calcular o produto que mais faturou
#criou se uma coluna de faturamento, ao multiplicar os valores da quantidade vendida e preco unitario
tabela_total["Faturamento"] = tabela_total["Quantidade Vendida"] * tabela_total["Preco Unitario"]
#display(tabela_total)

tabela_faturamento = tabela_total.groupby("Produto").sum()
tabela_faturamento = tabela_faturamento[["Faturamento"]].sort_values(by="Faturamento", ascending =False)

display(tabela_faturamento)

            Faturamento
Produto
iPhone         47562200
Televisão      14827500
Notebook       11371500
Android        10822200
Câmera          5890500
Tablet          4673600
SmartWatch      4172000

In [23]:
# passo 6 - Calcular a loja/cidade que mais vendeu (em faturamento) - criar gráfico/dashboard
tabela_lojas = tabela_total.groupby("Loja").sum()
tabela_lojas = tabela_lojas[["Faturamento"]]#.sort_values(by="Faturamento", ascending=False)
display(tabela_lojas)

                Faturamento
Loja
Belo Horizonte      6480300
Curitiba            7060500
Fortaleza          14087900
Goiás               7441800
Porto Alegre        6868600
Recife              7303000
Rio de Janeiro     14867800
Salvador           13111300
São Paulo          22098300

In [24]:
import plotly.express as px

In [25]:
grafico = px.bar(tabela_lojas, x=tabela_lojas.index, y="Faturamento")  #o nome "Loja" é o indice da tabela(esta a negrito) ou seja temos de chamar o index
grafico.show()